// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: kYz2v7iEZ8D57jf9vnLxce
// Component: a0KKIkdkjj
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: aoNG0OPj-BeO/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: kYz2v7iEZ8D57jf9vnLxce/projectcss
import * as sty from "./PlasmicPricing.module.css"; // plasmic-import: a0KKIkdkjj/css
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: 7R-Y0_Ur0GHe/icon
import Icon14Icon from "./icons/PlasmicIcon__Icon14"; // plasmic-import: -VoYvS87oLgx/icon

export const PlasmicPricing__VariantProps = new Array();

export const PlasmicPricing__ArgProps = new Array();

function PlasmicPricing__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(defaultcss.all, sty.box___3QhiV)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(defaultcss.all, sty.box__fKwnq)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__xkjpC)}
              >
                <div className={classNames(defaultcss.all, sty.box___82Ld6)}>
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___38AjQ
                    )}
                  >
                    {"Pricing plans"}
                  </div>
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__jJyVw
                  )}
                >
                  {
                    "Nascetur nascetur ridiculus scelerisque adipiscing a nascetur varius sed eu a ad semper a est nec litora ante at orci rhoncus a varius auctor aliquam inceptos vestibulum ridiculus."
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box___3E9Td)}
              >
                <div className={classNames(defaultcss.all, sty.box___2JXej)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__aglRv)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___5Y0Yf)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__wFosj
                        )}
                      >
                        {"Starter"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box___465P
                        )}
                      >
                        {"All the basics"}
                      </div>
                    </p.Stack>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__qOxGq
                      )}
                    >
                      {"Free"}
                    </div>

                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.link__zWbrN)}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___1KEil
                          )}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__pog7Y
                        )}
                      >
                        {"Get started"}
                      </div>

                      {false ? (
                        <IconIcon
                          className={classNames(defaultcss.all, sty.svg__ziF40)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>
                  </p.Stack>

                  <div className={classNames(defaultcss.all, sty.box__irRc)} />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__vdKrS)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__rgB2Z)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__jxkoT)}
                      >
                        <Icon14Icon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___97XxQ
                          )}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box__xfpFs)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___2LOd6
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box___64F1F)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__efs5K
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___7X1Tr
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__fXjQq)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__zMuB)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__zCgmo)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            sty.box___7Ety2
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___6Htn9
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__z7TFw)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__vCfeV
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___8T8Jo
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.box___7ErMv)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__mLkoo)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__uVjl)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__ickRk
                        )}
                      >
                        {"Pro"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__eJLqf
                        )}
                      >
                        {"Best deal"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__nt0W8)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box___7AqGc
                        )}
                      >
                        {"$8"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__u3K4S
                        )}
                      >
                        {"/mo"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.link__s69Us)}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(defaultcss.all, sty.svg__nFf23)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__sMcUb
                        )}
                      >
                        {"Purchase pro"}
                      </div>

                      {false ? (
                        <IconIcon
                          className={classNames(defaultcss.all, sty.svg__juLye)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>
                  </p.Stack>

                  <div className={classNames(defaultcss.all, sty.box__iqr9Y)} />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__r1GnT)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__ryXGf)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__ctOhd)}
                      >
                        <Icon14Icon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___7USjN
                          )}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box__vG9Pe)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__xnqi
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__rRpfh)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__siR0A
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__bqMer
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___3Dvhm)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__lyFun)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__fbsYt)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            sty.box___9Pz3J
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__onQz6
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__dJBeu)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__k1Qu5
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___2K2Ch
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__rru6C)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__a215C)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__yaYr)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            sty.box___0SNe8
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__pfbDe
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__ea38Z)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__mtgx9
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__tgCeC
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.box___79Efg)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__tc6Dv)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___4ZzKi)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__fix5C
                        )}
                      >
                        {"Team"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box___9T2Tx
                        )}
                      >
                        {"Level up"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__gyXIb)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__c8Uk6
                        )}
                      >
                        {"$16"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__pzUG
                        )}
                      >
                        {"/mo"}
                      </div>
                    </p.Stack>

                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.link__nioor)}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(defaultcss.all, sty.svg__wpkuA)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__utAeT
                        )}
                      >
                        {"Get started"}
                      </div>

                      {false ? (
                        <IconIcon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___7Vhol
                          )}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>
                  </p.Stack>

                  <div className={classNames(defaultcss.all, sty.box__ujCrm)} />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__xnsdP)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__nOuIe)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__v0T2)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__c3BLj)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box__hq8Pv)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg___9SzVj
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box___9P4M)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__asN5
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__sFyp
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__zw9TJ)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__zCwe3)}
                      >
                        <Icon14Icon
                          className={classNames(
                            defaultcss.all,
                            sty.svg___8NyNq
                          )}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box___9XAX)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__cfVq
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__y0Pbg)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__vjNk
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__diAlu
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__h9Tpn)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__y18S5)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg___7BuD)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box___77A5)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__icFf1
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box___8Sbh)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__oohS0
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__x0DPi
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__lo2Sn)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__hqyk8)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__aaNTu)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box__sUwIg)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__nnP29
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__pxrkl)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__kOqgh
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__qtl1
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </div>

                <div className={classNames(defaultcss.all, sty.box__tAefp)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__vk5Wc)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__s5Bio)}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__i5G1
                        )}
                      >
                        {"Enterprise"}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__ePeuI
                        )}
                      >
                        {"Fine-tune everything"}
                      </div>
                    </p.Stack>

                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__qYNk
                      )}
                    >
                      {"Custom"}
                    </div>

                    <p.Stack
                      as={"a"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.link__umgaB)}
                    >
                      {false ? (
                        <IconIcon
                          className={classNames(defaultcss.all, sty.svg__r4Sh)}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          defaultcss.all,
                          defaultcss.__wab_text,
                          sty.box__ok7X5
                        )}
                      >
                        {"Contact us"}
                      </div>

                      {false ? (
                        <IconIcon
                          className={classNames(defaultcss.all, sty.svg__sAuw)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>
                  </p.Stack>

                  <div className={classNames(defaultcss.all, sty.box__k9RTd)} />

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__wWchr)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__gv345)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__nS8Vw)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__g4E9L)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box__dVz9L)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__mvg2R
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__dq6O)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__khbH4
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__iMf4X
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___8J2Lf)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__dlAfA)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__vnmJm)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box__pw477)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__ryvZy
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__usUz9)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__dKeUh
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___7Ef86
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__t5RW)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box___9Ht1L)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__cr2T)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            sty.box___9YnJt
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__g1Ckl
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__sxzrx)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box___6UD8N
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__xd4Fr
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box___0ZJj7)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__v5J9A)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__z9Vwe)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            sty.box___9Zht4
                          )}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__j1V2R
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box__cqSrU)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__edQE
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__nxpDs
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__kTp5A)}
                    >
                      <div
                        className={classNames(defaultcss.all, sty.box__hb8S8)}
                      >
                        <Icon14Icon
                          className={classNames(defaultcss.all, sty.svg__asMg)}
                          role={"img"}
                        />
                      </div>

                      {false ? (
                        <div
                          className={classNames(defaultcss.all, sty.box__xiuTx)}
                        >
                          <Icon14Icon
                            className={classNames(
                              defaultcss.all,
                              sty.svg__kw44O
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}

                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(defaultcss.all, sty.box___9ZWyh)}
                      >
                        {false ? (
                          <div
                            className={classNames(
                              defaultcss.all,
                              defaultcss.__wab_text,
                              sty.box__qabJn
                            )}
                          >
                            {"Label"}
                          </div>
                        ) : null}

                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__rpNuk
                          )}
                        >
                          {"Nulla odio mauris."}
                        </div>
                      </p.Stack>
                    </p.Stack>
                  </p.Stack>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicPricing__ArgProps,
      internalVariantPropNames: PlasmicPricing__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicPricing__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicPricing";
  } else {
    func.displayName = `PlasmicPricing.${nodeName}`;
  }
  return func;
}

export const PlasmicPricing = Object.assign(
  // Top-level PlasmicPricing renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicPricing
    internalVariantProps: PlasmicPricing__VariantProps,
    internalArgProps: PlasmicPricing__ArgProps
  }
);

export default PlasmicPricing;
/* prettier-ignore-end */
